project_id = "gvkqcmssjjnmvkbdirrh"

[functions.invite-client]
verify_jwt = false

[functions.send-task-assignment]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false

[functions.send-task-reminders]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = false

[functions.export-all-data]
verify_jwt = false

[functions.capture-clio-assessment]
verify_jwt = false
